Repository TorchSim/torch-sim, pull requests merged in 2025-05, with the labels that each got.

#185 io Optional Dependencies in pyproject.toml
  pyproject.toml
  tests/test_io.py
  tests/test_trajectory.py
  torch_sim/io.py
  torch_sim/trajectory.py
Labels: cla-signed

#186 Update metatrain dependency
  examples/tutorials/metatensor_tutorial.py
  pyproject.toml
Labels: cla-signed

#175 Updates integrator logic per #171.
  tests/conftest.py
  tests/models/conftest.py
  tests/test_integrators.py
  tests/test_transforms.py
  torch_sim/integrators.py
  torch_sim/transforms.py
  torch_sim/unbatched/unbatched_integrators.py
Labels: cla-signed

#188 fix installing conflicting optional dependencies via uv in pyproject.toml
  pyproject.toml
Labels: cla-signed

#146 Directly compare ASE vs TorchSim Frechet cell FIRE relaxation
  .coverage
  .github/workflows/docs.yml
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.md
  examples/scripts/7_Others/7.6_Compare_ASE_to_VV_FIRE.py
  pyproject.toml
  tests/conftest.py
  tests/models/test_mace.py
  tests/test_optimizers.py
  tests/test_optimizers_vs_ase.py
  tests/unbatched/test_unbatched_mace.py
  torch_sim/optimizers.py
  torch_sim/unbatched/unbatched_optimizers.py
Labels: tests, cla-signed, geo-opt

#194 stricter dead link checks: swap `markdown-link-check` for `lychee`
  .github/workflows/link-check.yml
  .pre-commit-config.yaml
  examples/scripts/7_Others/7.3_Batched_neighbor_list.py
  examples/scripts/readme.md
  examples/tutorials/using_graphpes_tutorial.py
  tests/models/test_fairchem.py
  tests/test_neighbors.py
  tests/test_runners.py
  torch_sim/integrators.py
  torch_sim/math.py
  torch_sim/models/interface.py
  torch_sim/models/lennard_jones.py
  torch_sim/models/mace.py
  torch_sim/models/mattersim.py
  torch_sim/models/metatensor.py
  torch_sim/models/morse.py
  torch_sim/models/orb.py
  torch_sim/models/sevennet.py
  torch_sim/models/soft_sphere.py
  torch_sim/neighbors.py
  torch_sim/state.py
  torch_sim/trajectory.py
  torch_sim/transforms.py
  torch_sim/unbatched/models/lennard_jones.py
  torch_sim/unbatched/models/morse.py
  torch_sim/unbatched/models/particle_life.py
  torch_sim/unbatched/models/soft_sphere.py
  torch_sim/unbatched/unbatched_integrators.py
  torch_sim/workflows/a2c.py
Labels: docs, ci, cla-signed

#187 Fix Fairchem import possibly failing silently until it reaches setup_imports()
  CHANGELOG.md
  torch_sim/models/fairchem.py
  torch_sim/models/graphpes.py
  torch_sim/models/mace.py
  torch_sim/models/mattersim.py
  torch_sim/models/metatensor.py
  torch_sim/models/orb.py
  torch_sim/models/sevennet.py
  torch_sim/unbatched/models/mace.py
Labels: fix, cla-signed, ecosystem

#190 Test stresses in the ase consistency test.
  .github/workflows/test.yml
  examples/scripts/7_Others/7.6_Compare_ASE_to_VV_FIRE.py
  tests/models/conftest.py
  tests/models/test_fairchem.py
  tests/models/test_graphpes.py
  tests/models/test_mace.py
  tests/models/test_metatensor.py
  tests/models/test_orb.py
  tests/models/test_sevennet.py
  tests/test_optimizers_vs_ase.py
  tests/test_voigt.py
  tests/unbatched/conftest.py
  torch_sim/models/mace.py
  torch_sim/models/metatensor.py
  torch_sim/models/orb.py
  torch_sim/models/sevennet.py
Labels: cla-signed

#199 Fix unit and frechet cell FIRE optimizers not rescaling atom positions after each cell update
  tests/conftest.py
  tests/test_optimizers_vs_ase.py
  torch_sim/optimizers.py
Labels: tests, fix, cla-signed, geo-opt

#200 Difference in ASE FrechetCellFilter vs Torch-Sim (both md_flavors) + enhanced convergence testing
  examples/scripts/7_Others/7.6_Compare_ASE_to_VV_FIRE.py
  examples/tutorials/low_level_tutorial.py
  tests/models/test_graphpes.py
  torch_sim/models/sevennet.py
  torch_sim/optimizers.py
  torch_sim/properties/correlations.py
Labels: bug, cla-signed
