Repository TorchSim/torch-sim, pull requests merged in 2025-04, with the labels that each got.

#94 Model and testing fixes
  examples/tutorials/autobatching_tutorial.py
  examples/tutorials/high_level_tutorial.py
  tests/conftest.py
  tests/test_elastic.py
  torch_sim/autobatching.py
  torch_sim/models/orb.py
  torch_sim/models/sevennet.py
  torch_sim/state.py
Labels: cla-signed

#96 try docs build
  .github/workflows/docs.yml
Labels: cla-signed

#97 Finalize README and configure codecov hooks
  .github/workflows/link-check-config.json
  .github/workflows/test.yml
  README.md
  citation.cff
  docs/conf.py
  examples/scripts/5_Workflow/5.1_a2c_silicon.py
  examples/scripts/5_Workflow/5.2_a2c_silicon_batched.py
  examples/tutorials/reporting_tutorial.py
  pyproject.toml
  torch_sim/__init__.py
  torch_sim/_version.py
  torch_sim/models/interface.py
  torch_sim/models/morse.py
  torch_sim/models/soft_sphere.py
Labels: cla-signed

#91 Phonon examples: bands + DOS, quasi-harmonic, Wigner lattice conductivity
  docs/conf.py
  examples/scripts/6_Phonons/6.1_Phonon_dos_batched_MACE.py
  examples/scripts/6_Phonons/6.1_Phonons_MACE.py
  examples/scripts/6_Phonons/6.2_QuasiHarmonic_MACE.py
  examples/scripts/6_Phonons/6.2_Thermal_conductivity_MACE.py
  examples/scripts/6_Phonons/6.3_Conductivity_MACE.py
  examples/scripts/6_Phonons/6.3_Thermal_conductivity_batched_MACE.py
  examples/scripts/readme.md
Labels: cla-signed, examples

#99 Increase test coverage
  README.md
  tests/models/test_soft_sphere.py
  tests/test_transforms.py
  torch_sim/autobatching.py
  torch_sim/elastic.py
  torch_sim/io.py
  torch_sim/models/fairchem.py
  torch_sim/models/orb.py
  torch_sim/state.py
  torch_sim/trajectory.py
  torch_sim/unbatched/models/mace.py
Labels: tests, cla-signed

#100 Add speedup plot to README
  README.md
  docs/_static/speedup_plot.png
  pyproject.toml
Labels: cla-signed

#105 Refactor testing to use matrix and condense different model tests
  .github/workflows/test.yml
  pyproject.toml
  tests/models/test_fairchem.py
  tests/models/test_orb.py
  tests/models/test_sevennet.py
Labels: cla-signed

#108 Refactor example scripts imports
  README.md
  examples/scripts/1_Introduction/1.2_MACE.py
  examples/scripts/1_Introduction/1.3_Batched_MACE.py
  examples/scripts/1_Introduction/1.4_Fairchem.py
  examples/scripts/2_Structural_optimization/2.1_Lennard_Jones_FIRE.py
  examples/scripts/2_Structural_optimization/2.7_Batched_MACE_UnitCellFilter_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.8_Batched_MACE_UnitCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.9_Batched_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/5_Workflow/5.1_a2c_silicon.py
  examples/scripts/5_Workflow/5.2_a2c_silicon_batched.py
  examples/scripts/5_Workflow/5.3_Hot_Swap_WBM.py
  examples/scripts/5_Workflow/5.4_Elastic.py
  examples/scripts/6_Phonons/6.1_Phonons_MACE.py
  examples/scripts/6_Phonons/6.2_QuasiHarmonic_MACE.py
  examples/scripts/6_Phonons/6.3_Conductivity_MACE.py
Labels: cla-signed, refactor

#110 Update readmes across package and fix plot display in documentation
  README.md
  docs/_static/speedup_plot.svg
  docs/dev/dev_install.md
  docs/index.md
  docs/user/overview.md
  examples/readme.md
  examples/tutorials/autobatching_tutorial.py
  examples/tutorials/high_level_tutorial.py
  examples/tutorials/hybrid_swap_tutorial.py
  examples/tutorials/low_level_tutorial.py
  examples/tutorials/reporting_tutorial.py
  torch_sim/__init__.py
  torch_sim/models/__init__.py
  torch_sim/models/fairchem.py
  torch_sim/models/mace.py
  torch_sim/unbatched/readme.md
  torch_sim/workflows/__init__.py
  torch_sim/workflows/readme.md
Labels: cla-signed

#121 Model documentation fixes
  README.md
  docs/dev/add_model.md
  examples/tutorials/high_level_tutorial.py
  tests/test_runners.py
  torch_sim/models/fairchem.py
  torch_sim/models/interface.py
Labels: cla-signed

#126 FairChemModel Updates: PBC handling, test on OMat24 pre-trained model
  .github/workflows/test.yml
  tests/models/test_fairchem.py
  torch_sim/models/fairchem.py
  torch_sim/models/graphpes.py
  torch_sim/models/lennard_jones.py
  torch_sim/models/mace.py
  torch_sim/models/mattersim.py
  torch_sim/models/morse.py
  torch_sim/models/orb.py
  torch_sim/models/sevennet.py
  torch_sim/unbatched/models/lennard_jones.py
  torch_sim/unbatched/models/mace.py
  torch_sim/unbatched/models/morse.py
  torch_sim/unbatched/models/particle_life.py
  torch_sim/unbatched/models/soft_sphere.py
Labels: cla-signed

#115 Feature: Correlation function module
  docs/reference/index.rst
  examples/scripts/7_Others/7.4_Velocity_AutoCorrelation.py
  tests/test_correlations.py
  torch_sim/__init__.py
  torch_sim/properties/__init__.py
  torch_sim/properties/correlations.py
Labels: feature, cla-signed

#123 Support different temperatures in batches
  tests/conftest.py
  tests/test_integrators.py
  torch_sim/integrators.py
  torch_sim/models/sevennet.py
  torch_sim/runners.py
Labels: enhancement, fix, cla-signed

#134 Only install HF for fairchem tests
  .github/workflows/test.yml
Labels: cla-signed

#132 Plot `torch_sim` module graph
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/_static/get_module_graph_dot_file.py
  docs/_static/torch-sim-module-graph.dot
  docs/_static/torch-sim-module-graph.svg
  docs/reference/index.rst
  examples/readme.md
  examples/scripts/4_High_level_api/4.2_auto_batching_api.py
  examples/tutorials/autobatching_tutorial.py
  examples/tutorials/high_level_tutorial.py
  examples/tutorials/hybrid_swap_tutorial.py
  examples/tutorials/reporting_tutorial.py
  examples/tutorials/state_tutorial.py
  tests/test_autobatching.py
  torch_sim/autobatching.py
Labels: docs, cla-signed

#124 Add metatensor models
  .github/workflows/docs.yml
  .github/workflows/test.yml
  README.md
  docs/conf.py
  docs/index.md
  docs/tutorials/index.rst
  examples/tutorials/metatensor_tutorial.py
  pyproject.toml
  tests/models/test_metatensor.py
  torch_sim/models/__init__.py
  torch_sim/models/metatensor.py
Labels: cla-signed

#136 Revert "Add metatensor models (#124)"
  .github/workflows/docs.yml
  .github/workflows/test.yml
  README.md
  docs/conf.py
  docs/index.md
  docs/tutorials/index.rst
  examples/tutorials/metatensor_tutorial.py
  pyproject.toml
  tests/models/test_metatensor.py
  torch_sim/models/__init__.py
  torch_sim/models/metatensor.py
Labels: cla-signed

#139 Implement positions only FIRE
  examples/scripts/2_Structural_optimization/2.10_Batched_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.7_Batched_MACE_FIRE.py
  examples/scripts/2_Structural_optimization/2.8_Batched_MACE_UnitCellFilter_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.9_Batched_MACE_UnitCellFilter_FIRE.py
  tests/test_optimizers.py
  torch_sim/optimizers.py
  torch_sim/unbatched/unbatched_optimizers.py
Labels: cla-signed

#141 Add metatensor models
  .github/workflows/docs.yml
  .github/workflows/test.yml
  README.md
  docs/conf.py
  docs/index.md
  docs/tutorials/index.rst
  examples/tutorials/metatensor_tutorial.py
  pyproject.toml
  tests/models/test_metatensor.py
  torch_sim/models/__init__.py
  torch_sim/models/metatensor.py
Labels: cla-signed

#143 Reduce test flakiness and hotfix docs
  README.md
  docs/reference/index.rst
  examples/scripts/4_High_level_api/4.2_auto_batching_api.py
  examples/scripts/5_Workflow/5.3_In_Flight_WBM.py
  examples/tutorials/autobatching_tutorial.py
  tests/Interactive-1.interactive
  tests/models/test_graphpes.py
  tests/test_autobatching.py
  tests/test_runners.py
  torch_sim/__init__.py
  torch_sim/autobatching.py
  torch_sim/runners.py
Labels: docs, ci, cla-signed, breaking

#140 Orbv3 Updates
  tests/models/test_orb.py
  torch_sim/models/orb.py
Labels: cla-signed, ecosystem

#154 Mattersim fix
  tests/conftest.py
  torch_sim/models/mattersim.py
Labels: cla-signed

#153 fix `npt_langevin`
  tests/test_integrators.py
  tests/test_neighbors.py
  tests/test_state.py
  torch_sim/integrators.py
  torch_sim/models/interface.py
  torch_sim/properties/correlations.py
  torch_sim/state.py
  torch_sim/trajectory.py
  torch_sim/unbatched/unbatched_integrators.py
Labels: fix, cla-signed, md

#156 Make sure to move data to CPU before calling vesin
  examples/tutorials/metatensor_tutorial.py
  pyproject.toml
  torch_sim/models/metatensor.py
Labels: cla-signed

#163 Fix virial calculations in `optimizers` and `integrators`
  tests/test_io.py
  torch_sim/integrators.py
  torch_sim/optimizers.py
  torch_sim/unbatched/unbatched_optimizers.py
Labels: fix, cla-signed, md, geo-opt

#157 Add `torch_sim/typing.py`
  .github/workflows/docs.yml
  CHANGELOG.md
  examples/scripts/1_Introduction/1.1_Lennard_Jones.py
  examples/scripts/1_Introduction/1.2_MACE.py
  examples/scripts/1_Introduction/1.3_Batched_MACE.py
  examples/scripts/2_Structural_optimization/2.10_Batched_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.3_MACE_FIRE.py
  examples/scripts/2_Structural_optimization/2.4_MACE_UnitCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.5_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.6_Batched_MACE_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.8_Batched_MACE_UnitCellFilter_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.9_Batched_MACE_UnitCellFilter_FIRE.py
  examples/scripts/3_Dynamics/3.10_Hybrid_swap_mc.py
  examples/scripts/3_Dynamics/3.12_MACE_NPT_Langevin.py
  examples/scripts/3_Dynamics/3.2_MACE_NVE.py
  examples/scripts/3_Dynamics/3.3_MACE_NVE_cueq.py
  examples/scripts/3_Dynamics/3.4_MACE_NVT_Langevin.py
  examples/scripts/3_Dynamics/3.5_MACE_NVT_Nose_Hoover.py
  examples/scripts/3_Dynamics/3.6_MACE_NVT_Nose_Hoover_temp_profile.py
  examples/scripts/3_Dynamics/3.8_MACE_NPT_Nose_Hoover.py
  examples/scripts/3_Dynamics/3.9_MACE_NVT_staggered_stress.py
  examples/scripts/5_Workflow/5.1_a2c_silicon.py
  examples/scripts/5_Workflow/5.2_a2c_silicon_batched.py
  examples/scripts/5_Workflow/5.3_In_Flight_WBM.py
  examples/scripts/5_Workflow/5.4_Elastic.py
  examples/scripts/6_Phonons/6.1_Phonons_MACE.py
  examples/scripts/6_Phonons/6.2_QuasiHarmonic_MACE.py
  examples/scripts/6_Phonons/6.3_Conductivity_MACE.py
  examples/tutorials/low_level_tutorial.py
  tests/test_elastic.py
  tests/test_neighbors.py
  torch_sim/autobatching.py
  torch_sim/elastic.py
  torch_sim/integrators.py
  torch_sim/models/fairchem.py
  torch_sim/models/graphpes.py
  torch_sim/models/interface.py
  torch_sim/models/lennard_jones.py
  torch_sim/models/mace.py
  torch_sim/models/mattersim.py
  torch_sim/models/metatensor.py
  torch_sim/models/morse.py
  torch_sim/models/orb.py
  torch_sim/models/sevennet.py
  torch_sim/models/soft_sphere.py
  torch_sim/neighbors.py
  torch_sim/optimizers.py
  torch_sim/quantities.py
  torch_sim/runners.py
  torch_sim/state.py
  torch_sim/trajectory.py
  torch_sim/transforms.py
  torch_sim/typing.py
  torch_sim/unbatched/models/mace.py
  torch_sim/unbatched/models/morse.py
  torch_sim/unbatched/models/soft_sphere.py
  torch_sim/unbatched/unbatched_integrators.py
  torch_sim/unbatched/unbatched_optimizers.py
  torch_sim/workflows/a2c.py
Labels: cla-signed, types

#165 Improves Orb's state_to_atoms_graph calculation
  torch_sim/models/orb.py
Labels: cla-signed

#160 Pad memory estimation
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  tests/models/test_mace.py
  tests/test_autobatching.py
  torch_sim/autobatching.py
  torch_sim/runners.py
Labels: cla-signed

#167 throw error if autobatcher type is wrong
  tests/test_runners.py
  torch_sim/autobatching.py
  torch_sim/runners.py
Labels: enhancement, cla-signed

#168 Better module fig
  .github/workflows/docs.yml
  README.md
  docs/_static/draw_pkg_treemap.py
  docs/_static/torch-sim-module-graph.dot
  docs/_static/torch-sim-module-graph.svg
  docs/reference/index.rst
  tests/models/conftest.py
  tests/unbatched/conftest.py
  torch_sim/__init__.py
  torch_sim/runners.py
Labels: docs, cla-signed

#170 Bump `mace-torch` to v0.3.12
  examples/scripts/1_Introduction/1.2_MACE.py
  examples/scripts/1_Introduction/1.3_Batched_MACE.py
  examples/scripts/2_Structural_optimization/2.10_Batched_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.3_MACE_FIRE.py
  examples/scripts/2_Structural_optimization/2.4_MACE_UnitCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.5_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.6_Batched_MACE_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.7_Batched_MACE_FIRE.py
  examples/scripts/2_Structural_optimization/2.8_Batched_MACE_UnitCellFilter_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.9_Batched_MACE_UnitCellFilter_FIRE.py
  examples/scripts/3_Dynamics/3.10_Hybrid_swap_mc.py
  examples/scripts/3_Dynamics/3.12_MACE_NPT_Langevin.py
  examples/scripts/3_Dynamics/3.13_MACE_NVE_non_pbc.py
  examples/scripts/3_Dynamics/3.2_MACE_NVE.py
  examples/scripts/3_Dynamics/3.3_MACE_NVE_cueq.py
  examples/scripts/3_Dynamics/3.4_MACE_NVT_Langevin.py
  examples/scripts/3_Dynamics/3.5_MACE_NVT_Nose_Hoover.py
  examples/scripts/3_Dynamics/3.6_MACE_NVT_Nose_Hoover_temp_profile.py
  examples/scripts/3_Dynamics/3.8_MACE_NPT_Nose_Hoover.py
  examples/scripts/3_Dynamics/3.9_MACE_NVT_staggered_stress.py
  examples/scripts/4_High_level_api/4.1_high_level_api.py
  examples/scripts/4_High_level_api/4.2_auto_batching_api.py
  examples/scripts/5_Workflow/5.1_a2c_silicon.py
  examples/scripts/5_Workflow/5.4_Elastic.py
  examples/scripts/6_Phonons/6.1_Phonons_MACE.py
  examples/scripts/6_Phonons/6.2_QuasiHarmonic_MACE.py
  examples/scripts/6_Phonons/6.3_Conductivity_MACE.py
  examples/tutorials/autobatching_tutorial.py
  examples/tutorials/high_level_tutorial.py
  examples/tutorials/hybrid_swap_tutorial.py
  examples/tutorials/low_level_tutorial.py
  examples/tutorials/reporting_tutorial.py
  examples/tutorials/state_tutorial.py
  pyproject.toml
  torch_sim/autobatching.py
Labels: cla-signed

#172 Refactor sevennet model
  torch_sim/models/sevennet.py
Labels: cla-signed

#177 Try out hatchling for build vs setuptools
  .github/workflows/docs.yml
  pyproject.toml
Labels: cla-signed, pkg

#179 [BREAKING] Remove higher level model imports
  README.md
  examples/scripts/1_Introduction/1.3_Batched_MACE.py
  examples/scripts/1_Introduction/1.4_Fairchem.py
  examples/scripts/2_Structural_optimization/2.10_Batched_MACE_FrechetCellFilter_FIRE.py
  examples/scripts/2_Structural_optimization/2.7_Batched_MACE_FIRE.py
  examples/scripts/2_Structural_optimization/2.8_Batched_MACE_UnitCellFilter_Gradient_Descent.py
  examples/scripts/2_Structural_optimization/2.9_Batched_MACE_UnitCellFilter_FIRE.py
  examples/scripts/5_Workflow/5.2_a2c_silicon_batched.py
  examples/scripts/5_Workflow/5.3_In_Flight_WBM.py
  examples/scripts/5_Workflow/5.4_Elastic.py
  examples/scripts/6_Phonons/6.1_Phonons_MACE.py
  examples/scripts/6_Phonons/6.2_QuasiHarmonic_MACE.py
  examples/scripts/6_Phonons/6.3_Conductivity_MACE.py
  examples/tutorials/autobatching_tutorial.py
  examples/tutorials/low_level_tutorial.py
  examples/tutorials/metatensor_tutorial.py
  examples/tutorials/reporting_tutorial.py
  examples/tutorials/using_graphpes_tutorial.py
  torch_sim/elastic.py
  torch_sim/math.py
  torch_sim/models/__init__.py
  torch_sim/models/graphpes.py
  torch_sim/unbatched/models/lennard_jones.py
  torch_sim/unbatched/models/morse.py
  torch_sim/unbatched/models/particle_life.py
  torch_sim/unbatched/models/soft_sphere.py
  torch_sim/workflows/a2c.py
Labels: cla-signed, breaking
